### ISSUE TITLE
readLandBlock height undefined

### ISSUE THREAD

**Issue by lamo2k123** [kevinhikaruevans/uodatareader#4]
https://github.com/kevinhikaruevans/uodatareader/blob/master/map.js#L27 `this.height === undefined`

**Comment by lamo2k123** [comment]
I corrected in his branch: https://github.com/kevinhikaruevans/uodatareader/commit/f73b51f4592920fc6d69ae0daa8bcf8be6fd3304#diff-aaefedc0b7ff574c29fe176b27237bf4R92

**Comment by kevinhikaruevans** [comment]
Thanks for catching that! 👍 

Should be fixed now
